# Introdução à NumPy

<br><br>

#### Prof. Vicente Helano
UFCA | Centro de Ciências e Tecnologia

## Importando a NumPy

In [3]:
import numpy as np # chamando a numpy de np

## Tipos de dados

Seus tipos primitivos são:

`bool`
`int32`
`int64`
`uint32`
`uint64`
`float32`
`float64`
`complex64`
`complex128`

## Tipos de dados

mas o mais útil é o:

`numpy.array`

## Constantes

A NumPy possui diversas constantes matemáticas pré-definidas.

In [ ]:
np.pi,np.e

## Funções matemáticas

Também há diversas funções prontas:

In [5]:
teta = np.pi/2

print("%25.20e" % np.sin(teta))

1.00000000000000000000e+00


## Lidando com arranjos

A `numpy.array` é um arranjo numérico **homogêneo**.
Apesar de ser um tipo *mutável*, o tamanho de um arranjo NumPy é **imutável** e, por isso, não pode ser vazio.

### Construção de arranjos

A partir de listas de listas:

In [4]:
# Matrizes: [ [linha 0], [linha 1], ..., [linha n-1] ]
A = np.array([ [1, 2, 3], [4, 5, 6], [7, 8, 9] ])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Construção de arranjos

A partir de outro `numpy.array`:

In [ ]:
B = np.array(A) # cópia de A
B,A

### Construção de arranjos

Usando funções *especiais*:

In [ ]:
np.arange(10) # a sintaxe é semelhante à da `range`

### Construção de arranjos

Usando funções *especiais*:

In [ ]:
O = np.zeros((4,5),dtype=float) # o par (4, 5) indica os números de linhas e colunas desejados
I = np.eye(4) # identidade
U = np.ones((4,5)) # 1's
O,I,U

### Construção de arranjos

Usando funções *especiais*:

In [ ]:
np.linspace(-1, 1, 10)

### Alterando as dimensões de um arranjo

In [6]:
A = np.array([[1,3.5],[-1,0],[1,3.]])
A

array([[ 1. ,  3.5],
       [-1. ,  0. ],
       [ 1. ,  3. ]])

In [7]:
A.size, A.shape

(6, (3, 2))

### Alterando as dimensões de um arranjo

In [ ]:
A = np.linspace(1.0, 4.0, 16)
A

### Alterando as dimensões de um arranjo

In [ ]:
A.reshape(2,8)

### Alterando as dimensões de um arranjo

In [ ]:
A.flatten()

### Acessando elementos de um arranjo

In [8]:
A = np.array([[8, 2, 3],[9, 7, 2],[5, 5, 7],[4, 5, 9]])
A

array([[8, 2, 3],
       [9, 7, 2],
       [5, 5, 7],
       [4, 5, 9]])

In [9]:
A[3,2]

9

### Operações com arranjos

In [ ]:
A = np.array([[1, 1, 1, 1],[1, 1, 1, 1],[1, 1, 1, 1],[1, 1, 1, 1]])
B = np.array([[7, 1, 3, 0],[6, 0, 2, 6],[2, 2, 1, 9],[8, 6, 7, 1]])
print(A)
print(B)

In [ ]:
B+1 == A+B # soma de matrizes

### Operações com arranjos

In [ ]:
A = np.array([[1, 1, 1, 1],[2, 2, 2, 2],[3, 3, 3, 3],[4, 4, 4, 4]])
B = np.array([[7, 1, 3, 0],[6, 0, 2, 6],[2, 2, 1, 9],[8, 6, 7, 1]])

In [ ]:
A*B # produto coeficiente a coeficiente cij = aij * bij

### Operações com arranjos

Produto matricial $\mathbf{A}\mathbf{B}$:

In [ ]:
A = np.array([[1, 1, 1, 1],[2, 2, 2, 2],[3, 3, 3, 3],[4, 4, 4, 4]])
B = np.array([[7, 1, 3, 0],[6, 0, 2, 6],[2, 2, 1, 9],[8, 6, 7, 1]])

In [ ]:
np.dot(A,B) # Resultado = AB

### Operações com arranjos

Se dois arranjos $\mathbf{v}$ e $\mathbf{w}$ forem unidimensionais (vetor linha), o resultado será o produto escalar entre eles:

In [ ]:
v = np.array([1, 1, 1, 1])
w = np.array([7, 1, 3, 0])

In [ ]:
np.dot(v,w) # Resultado = <u,v>

## Exercício

(a) Aplique o que você aprendeu sobre arranjos da numpy para completar a função `matpot` a seguir. Ela deve **retornar** a $k$-ésima potência de uma matriz $\mathbf{A}$, $n\times n$. Você deve realizar o produto de matrizes utilizando a função `np.dot`.

In [ ]:
def matpot(A,k):
    """
    Calcula a k-ésima potência da matriz A.
    
       Argumentos:
         A (numpy.array): matriz quadrada armazenada usando o `array` da numpy.
         k (int): valor da potência desejada, k >= 0.
         
       Retorno:
         (numpy.array): o valor de A^k
    """
    # você deve iniciar a implementação desta função a partir daqui.
    

(b) Aplique sua implementação da `matpot` nas matrizes:

$$
\mathbf{A} = \begin{bmatrix}
 2 & -1 & 0 \\
-1 &  2 &  -1 \\
 0 & -1 & 2
\end{bmatrix},
\qquad
\mathbf{B} = \begin{bmatrix}
 2 & -2 & -4 \\
-1 &  3 &  4 \\
 1 & -2 & -3
\end{bmatrix}
\quad
\text{e}
\quad
\mathbf{C} = \begin{bmatrix}
0 & 1 & 0 \\
0 & 0 & 2 \\
0 & 0 & 0
\end{bmatrix},
\qquad
$$

com $k = 30$.

In [ ]:
# Escreva o código de verificação aqui embaixo.


(c) Você percebeu algum fato interessante? Discuta com seus colegas.

## Saiba mais

- Ao longo do curso, aprenderemos muito mais sobre a NumPy. Se você ficou curioso e quer saber mais sobre ela, sugiro que acesse: __[https://www.numpy.org/](https://www.numpy.org/)__

* As matrizes $\mathbf{B}$ e $\mathbf{C}$ acima recebem o nome de *idempotente* e *nilpotente*, respectivamente. Assista ao vídeo abaixo sobre algumas das matrizes especiais que veremos ao longo de nosso curso:

In [ ]:
from IPython.display import HTML, IFrame 
IFrame(src="https://www.youtube.com/embed/0IcsJpNjXmY", width=320, height=240)

Vicente Helano  
UFCA | Centro de Ciências e Tecnologia